# Generated by Django 3.2.7 on 2021-09-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_lectureclasssession_id'),
        ('students', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassVideo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('lecture_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lectureclasssession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('lecture_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lectureclasssession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
