# Generated by Django 3.2.7 on 2021-09-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_lectureclasssession'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_link', models.CharField(max_length=2000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ClassVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('subject', models.CharField(default=' - ', max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
                ('lecture_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lectureclasssession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000)),
                ('subject', models.CharField(default=' - ', max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
                ('lecture_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lectureclasssession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
