# Generated by Django 3.2.7 on 2021-09-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplink',
            name='class_link',
            field=models.TextField(default=' - '),
        ),
        migrations.AddField(
            model_name='grouplink',
            name='source_link',
            field=models.TextField(default=' - '),
        ),
        migrations.AlterField(
            model_name='grouplink',
            name='telegram_link',
            field=models.TextField(default=' - '),
        ),
    ]
