# Generated by Django 3.2.7 on 2021-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20210908_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnote',
            name='subject',
            field=models.CharField(default=' - ', max_length=1000),
        ),
        migrations.AddField(
            model_name='classvideo',
            name='subject',
            field=models.CharField(default=' - ', max_length=1000),
        ),
    ]
