# Generated by Django 3.2.7 on 2021-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20210918_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplink',
            name='calendar_link',
            field=models.TextField(default=' - '),
        ),
        migrations.AddField(
            model_name='grouplink',
            name='course_outline_link',
            field=models.TextField(default=' - '),
        ),
    ]
