# Generated by Django 3.2.7 on 2021-09-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(default=-1)),
                ('lectures', models.ManyToManyField(to='courses.Lecture')),
            ],
        ),
    ]
