# Generated by Django 3.2.6 on 2021-08-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedbacklike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='text',
        ),
    ]
