# Generated by Django 3.2.6 on 2021-08-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='group_id',
            field=models.IntegerField(),
        ),
    ]
