# Generated by Django 3.2.7 on 2021-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lectureclasssession'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='mail',
            field=models.EmailField(default=' - ', max_length=254),
        ),
    ]
