# Generated by Django 3.2.7 on 2021-09-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lecture_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureclasssession',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
