# Generated by Django 3.2.7 on 2021-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuserstate',
            name='state',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Giving Feedback'), (2, 'Authorizing'), (3, 'Archiving')]),
        ),
    ]
